# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.8
-   repo: https://gitlab.com/iamlikeme/nbhooks
    rev: 1.0.0
    hooks:
    - id: nb-ensure-clean
-   repo: local
    hooks:
    - id: unittest
      name: unittest
      entry: poetry run python -m unittest
      'types': [python]
      language: system 
